server:
  port: 5000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

rest:
  existing-apis:
    base-url : ${existing-apis.base-url}
    similarId: ${existing-apis.similarIds}